#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org
 
START=10
STOP=15
 
start() {        
        echo start
        /root/bw_monitor.sh
}                 
 
stop() {          
        echo stop
        rm -f /tmp/monitor-started.lock
        sleep 15
}
